name: Mettre à jour le calendrier filtré

on:
  schedule:
    - cron: "0 6 * * *"   # Tous les jours à 6h du matin UTC
  workflow_dispatch:      # Permet de le lancer manuellement depuis GitHub
  push:                   # Se lance aussi si tu modifies le dépôt

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Installer les dépendances
        run: pip install -r requirements.txt

      - name: Exécuter le script
        run: python script.py

      - name: Commit et push du nouveau calendrier
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add docs/filtré.ics
          git commit -m "Mise à jour automatique du calendrier" || echo "Aucun changement"
          git push
